### PR TITLE
Expose ReadBody on ScenarioAssertionException

### LINKED ISSUE #132: Does this look correct: a ContentShouldBeJson assertion helper
Hi there,

First off, great library!

For a project, I needed a way to verify that the structure of the raw JSON returned from a request matches our API contract, so I created the following custom extension method. 

However, I had to copy in the `ReadBody` method since it was internal, which leads me to believe it should either be public, or I am doing something wrong.

Here is my custom assertion helper, which uses the https://github.com/weichch/system-text-json-jsondiffpatch library to perform the JSON comparison:

```c#
internal static class AlbaScenarioAssertionExtensions
{
    private static readonly JsonSerializerOptions PrettyPrintOptions = new JsonSerializerOptions() { WriteIndented = true };

    public static Scenario ContentShouldBeJson(this Scenario scenario, string jsonString)
    {
        return scenario.AssertThat(new BodyJsonAssertion(jsonString));
    }

    private class BodyJsonAssertion : IScenarioAssertion
    {
        private readonly string jsonString;

        public BodyJsonAssertion(string jsonString)
        {
            this.jsonString = jsonString;
        }

        public void Assert(Scenario scenario, HttpContext context, ScenarioAssertionException ex)
        {
            var body = ReadBody(context);
            var actual = JsonNode.Parse(body);
            var expected = JsonNode.Parse(jsonString);

            if (!actual.DeepEquals(expected, JsonElementComparison.RawText))
            {
                ex.Add($"Expected the content to be:{Environment.NewLine}" +
                    $"{expected.ToJsonString(PrettyPrintOptions)}{Environment.NewLine}" +
                    $"but was:{Environment.NewLine}{actual.ToJsonString(PrettyPrintOptions)}");
            }
        }

        internal static string ReadBody(HttpContext context)
        {
            try
            {
                var stream = context.Response.Body;
                if (stream.CanSeek)
                {
                    stream.Position = 0;
                }

                return Encoding.UTF8.GetString(ReadAllBytes(stream));
            }
            catch (Exception)
            {
                return string.Empty;
            }
        }

        internal static byte[] ReadAllBytes(Stream stream)
        {
            using var content = new MemoryStream();
            stream.CopyTo(content);
            return content.ToArray();
        }
    }
}
```

Does this look OK or should I be doing something differently here?

### PR DESCRIPTION
**Pull request by Hawxy**
Closes #132

### CODE REVIEW

File: src/Alba/ScenarioAssertionException.cs [hunk 1]
```diff
@@ -65,11 +66,17 @@ public override string Message
...
         public string? Body { get; set; }
 
-        internal string ReadBody(HttpContext context)
+        /// <summary>
+        /// Reads the response body and returns it as a string
+        /// </summary>
+        /// <param name="context">The context of the response</param>
+        /// <returns>A string with the content of the body</returns>
+        [MemberNotNull(nameof(Body))]
+        public string ReadBody(HttpContext context)
```
Comment (egil) [inline src/Alba/ScenarioAssertionException.cs:79]: It's kind of annoying that I have to call `ReadBody` to assign the `Body` property and its not very discoverable to end users that this is required and that there is a relationship between the two.

The ReadBody method itself is useful since it will rewind the stream back to the beginning, which could affect other assertions helpers. Perhaps ReadBody should actually be an extension method on HttpContext instead and have a similar to the helper methods in `System.Net.Http.Json`, e.g. `ReadResponseBodyAsText`.

**Comment by jeremydmiller** [comment]
@Hawxy @egil This would have to wait for V8 like you already said, but I think I'd vote to eliminate the `Body` property and have folks rely on `GetBody()` -- or rename that as `ReadBodyAsString()` or something. Need to tip off folks that it requires some work to get there. And it's been awkward over the years for folks that try to read the body multiple times in the same test.

I think I also like the idea of any assertions in Scenario that assert on the contents of the body that they do their thing, but then we rewind the response stream so as not to trip up users doing secondary reads of that content. 

That's all from thinking about this for just a minute or two though.
